export const itemNameById: Record<number, string> = {
  0x0B: "Bow",
  0x64: "Progressive Bow",
  0x65: "Progressive Bow (Alt)",
  0x58: "Silver Arrows",
  0x3B: "Silver Bow",
  0x1D: "Book of Mudora",
  0x09: "Hammer",
  0x0A: "Hookshot",
  0x1A: "Magic Mirror",
  0x14: "Flute",
  0x4B: "Pegasus Boots",
  0x1B: "Power Glove",
  0x19: "Cape",
  0x29: "Mushroom",
  0x13: "Shovel",
  0x12: "Lamp",
  0x0D: "Magic Powder",
  0x1F: "Moon Pearl",
  0x15: "Cane of Somaria",
  0x07: "Fire Rod",
  0x1E: "Flippers",
  0x08: "Ice Rod",
  0x1C: "Titans Mitts",
  0x0F: "Bombos",
  0x10: "Ether",
  0x11: "Quake",
  0x16: "Bottle",
  0x2B: "Bottle (Red Potion)",
  0x2C: "Bottle (Green Potion)",
  0x2D: "Bottle (Blue Potion)",
  0x3D: "Bottle (Fairy)",
  0x3C: "Bottle (Bee)",
  0x48: "Bottle (Good Bee)",
  0x50: "Master Sword",
  0x02: "Tempered Sword",
  0x49: "Fighter Sword",
  0x03: "Golden Sword",
  0x5E: "Progressive Sword",
  0x61: "Progressive Glove",
  0x6A: "Triforce",
  0x6B: "Power Star",
  0x6C: "Triforce Piece",
  0x43: "Single Arrow",
  0x44: "Arrows (10)",
  0x54: "Arrow Upgrade (+10)",
  0x53: "Arrow Upgrade (+5)",
  0x4D: "Arrow Upgrade (70)",
  0x27: "Single Bomb",
  0x28: "Bombs (3)",
  0x31: "Bombs (10)",
  0x52: "Bomb Upgrade (+10)",
  0x51: "Bomb Upgrade (+5)",
  0x4C: "Bomb Upgrade (50)",
  0x22: "Blue Mail",
  0x23: "Red Mail",
  0x60: "Progressive Mail",
  0x0C: "Blue Boomerang",
  0x2A: "Red Boomerang",
  0x04: "Blue Shield",
  0x05: "Red Shield",
  0x06: "Mirror Shield",
  0x5F: "Progressive Shield",
  0x21: "Bug Catching Net",
  0x18: "Cane of Byrna",
  0x3E: "Boss Heart Container",
  0x3F: "Sanctuary Heart Container",
  0x17: "Piece of Heart",
  0x34: "Rupee (1)",
  0x35: "Rupees (5)",
  0x36: "Rupees (20)",
  0x41: "Rupees (50)",
  0x40: "Rupees (100)",
  0x46: "Rupees (300)",
  0x59: "Rupoor",
  0x5B: "Red Clock",
  0x5C: "Blue Clock",
  0x5D: "Green Clock",
  0x62: "Single RNG",
  0x63: "Multi RNG",
  0x4E: "Magic Upgrade (1/2)",
  0x4F: "Magic Upgrade (1/4)",
  0xA2: "Small Key (Eastern Palace)",
  0x9D: "Big Key (Eastern Palace)",
  0x8D: "Compass (Eastern Palace)",
  0x7D: "Map (Eastern Palace)",
  0xA3: "Small Key (Desert Palace)",
  0x9C: "Big Key (Desert Palace)",
  0x8C: "Compass (Desert Palace)",
  0x7C: "Map (Desert Palace)",
  0xAA: "Small Key (Tower of Hera)",
  0x95: "Big Key (Tower of Hera)",
  0x85: "Compass (Tower of Hera)",
  0x75: "Map (Tower of Hera)",
  0xA0: "Small Key (Hyrule Castle)",
  0x9F: "Big Key (Hyrule Castle)",
  0x8F: "Compass (Hyrule Castle)",
  0x7F: "Map (Hyrule Castle)",
  0xA4: "Small Key (Agahnims Tower)",
  0x9B: "Big Key (Agahnims Tower)",
  0x8B: "Compass (Agahnims Tower)",
  0x7B: "Map (Agahnims Tower)",
  0xA6: "Small Key (Palace of Darkness)",
  0x99: "Big Key (Palace of Darkness)",
  0x89: "Compass (Palace of Darkness)",
  0x79: "Map (Palace of Darkness)",
  0xAB: "Small Key (Thieves Town)",
  0x94: "Big Key (Thieves Town)",
  0x84: "Compass (Thieves Town)",
  0x74: "Map (Thieves Town)",
  0xA8: "Small Key (Skull Woods)",
  0x97: "Big Key (Skull Woods)",
  0x87: "Compass (Skull Woods)",
  0x77: "Map (Skull Woods)",
  0xA5: "Small Key (Swamp Palace)",
  0x9A: "Big Key (Swamp Palace)",
  0x8A: "Compass (Swamp Palace)",
  0x7A: "Map (Swamp Palace)",
  0xA9: "Small Key (Ice Palace)",
  0x96: "Big Key (Ice Palace)",
  0x86: "Compass (Ice Palace)",
  0x76: "Map (Ice Palace)",
  0xA7: "Small Key (Misery Mire)",
  0x98: "Big Key (Misery Mire)",
  0x88: "Compass (Misery Mire)",
  0x78: "Map (Misery Mire)",
  0xAC: "Small Key (Turtle Rock)",
  0x93: "Big Key (Turtle Rock)",
  0x83: "Compass (Turtle Rock)",
  0x73: "Map (Turtle Rock)",
  0xAD: "Small Key (Ganons Tower)",
  0x92: "Big Key (Ganons Tower)",
  0x82: "Compass (Ganons Tower)",
  0x72: "Map (Ganons Tower)",
  0xAF: "Small Key (Universal)",
  0x5A: "Nothing",
  0xB0: "Bee Trap",
  0xB1: "Faerie",
  0xB2: "Good Bee",
  0xB3: "Magic Jar",
  0xB4: "Apple",
  0x2E: "Red Potion",
  0x2F: "Green Potion",
  0x30: "Blue Potion",
  0x0E: "Bee",
  0x42: "Small Heart",
  0x4A: "Activated Flute",
};